- hosts: all
  tasks:
    - include_vars: ../conf/instance_settings.yml
    - name: Ensure the binarydir exists
      file:
        path: "{{ binarydir }}"
        state: directory

    - name: Ensure the log directory exists
      file:
        path: "{{ binarydir }}/logs"
        state: directory

    - name: Ensure the conf directory exists
      file:
        path: "{{ binarydir }}/conf"
        state: directory

- hosts: node_exporter
  tasks:
    - include_vars: ../conf/instance_settings.yml

    - name: Install prometheus node exporter
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ host_os }}.tar.gz"
        dest: "{{ binarydir }}"
        remote_src: yes

- hosts: prometheus
  tasks:
    - include_vars: ../conf/instance_settings.yml

    - name: Install prometheus
      unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.{{ host_os }}.tar.gz"
        dest: "{{ binarydir }}"
        remote_src: yes

- hosts: grafana
  tasks:
    - include_vars: ../conf/instance_settings.yml

    - name: Install grafana
      unarchive:
        src: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.{{ host_os }}.tar.gz"
        dest: "{{ binarydir }}"
        remote_src: yes

    - name: Copy grafana config file
      copy:
        src: ../conf/defaults.ini
        dest: "{{ binarydir }}/conf"

    - name: Copy grafana datasources
      copy:
        src: ../conf/datasources.yml
        dest: "{{ binarydir }}/grafana-{{ grafana_version }}/conf/provisioning/datasources"

    - name: Copy grafana default dashboard
      copy:
        src: ../conf/grafana_default.json
        dest: "{{ binarydir }}/conf"