{
 "title": "Asterix Stats",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Storage Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Asterix Storage Size",
   "type": "graph",
   "description": "This panel shows the number of bytes Asterix used in storage for each dataset, index, partition.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "asterix_storage_size",
     "legendFormat": "instance={{instance}}, dataset={{dataset}}, index={{index}}, partition={{partition}}"
    }
   ]
  },
  { "title": "Job Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Asterix Job Count Increase",
   "type": "graph",
   "description": "This panel shows the number of jobs that were run in the specified time interval (30 seconds).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "yaxes": [
    { "format": "jobs" }
   ],
   "targets": [
    {
     "expr": "increase(asterix_job_total_count[30s])",
     "legendFormat": "instance={{instance}}, status={{status}}"
    }
   ]
  },
  {
   "title": "Asterix Job Count",
   "type": "graph",
   "description": "This panel shows the count of jobs of each status at the specific time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "yaxes": [
    { "format": "jobs" }
   ],
   "targets": [
    {
     "expr": "asterix_job_count",
     "legendFormat": "instance={{instance}}, status={{status}}"
    }
   ]
  },
  {
   "title": "Asterix Cumulative Job Time Increase",
   "type": "graph",
   "description": "This panel shows the increase in the amount of time jobs are taking in the time interval (which is 30 seconds).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(asterix_job_total_milliseconds[30s]) / 1000",
     "legendFormat": "instance={{instance}}, status={{status}}"
    }
   ]
  },
  {
   "title": "Asterix Average Time Taken Per Job",
   "type": "graph",
   "description": "This panel shows the average amount of time each job is taking. If no jobs are running, it will show 0.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(asterix_job_total_milliseconds[30s])) by (status,instance)) /\n(sum(rate(asterix_job_total_count[30s])) by (status, instance)) / 1000",
     "legendFormat": "instance={{instance}}, status={{status}}"
    }
   ]
  },
  { "title": "File Descriptor Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "File Descriptor Usage",
   "type": "graph",
   "description": "This panel shows the Asterix file descriptor usage (number of file descriptors open / pre set file descriptor max set by Prometheus)",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds / process_max_fds) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Asterix CPU Usage Percentage",
   "type": "graph",
   "description": "This panel show the Asterix cpu usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(process_cpu_seconds_total[1m]) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "This panel shows the system cpu usage (per cpu)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Asterix Non Idle CPU Usage",
   "type": "graph",
   "description": "This panel shows the proportion of non idle cpu that Asterix is using",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(irate(process_cpu_seconds_total[1m]) * 100) / ignoring (instance, job) group_left avg(1-irate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}