{
 "title": "Asterix Job Stats",
 "tags": [
  "asterix",
  "cc"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Asterix Job Completions in last 30 Seconds",
   "type": "graph",
   "description": "This panel shows the number of jobs that were completed in the specified time interval (30 seconds).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "yaxes": [
    { "format": "jobs" }
   ],
   "targets": [
    {
     "expr": "increase(asterix_job_total_count[30s])",
     "legendFormat": "instance={{instance}}, status={{status}}"
    }
   ]
  },
  {
   "title": "Asterix Job Count for Running and Pending Jobs",
   "type": "graph",
   "description": "This panel shows the count of jobs of running and pending jobs at the specific time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "yaxes": [
    { "format": "jobs" }
   ],
   "targets": [
    {
     "expr": "asterix_job_count",
     "legendFormat": "instance={{instance}}, status={{status}}"
    }
   ]
  },
  {
   "title": "Asterix Cumulative Job Time Increase",
   "type": "graph",
   "description": "This panel shows the increase in the amount of time jobs are taking in the time interval (which is 30 seconds). This metric is only for archived jobs as we need the starting and ending time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(asterix_job_total_milliseconds[30s]) / 1000",
     "legendFormat": "instance={{instance}}, status={{status}}"
    }
   ]
  },
  {
   "title": "Asterix Average Time Taken Per Job",
   "type": "graph",
   "description": "This panel shows the average amount of time each job is taking. If no jobs are running, it will show 0. This metric is only for archived jobs as we need the starting and ending times.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(asterix_job_total_milliseconds[30s])) by (status,instance)) /\n(sum(rate(asterix_job_total_count[30s])) by (status, instance)) / 1000",
     "legendFormat": "instance={{instance}}, status={{status}}"
    }
   ]
  }
 ]
}