{
 "title": "Asterix System Stats",
 "tags": [
  "asterix",
  "system"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Asterix CPU Usage Percentage",
   "type": "graph",
   "description": "This panel shows the Asterix cpu usage",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "graph",
   "description": "This panel shows the system cpu usage (per cpu)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "Asterix Non Idle CPU Usage",
   "type": "graph",
   "description": "This panel shows the proportion of non idle cpu that Asterix is using",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(rate(process_cpu_seconds_total[1m]) * 100) / ignoring (instance, job) group_left avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "File Descriptor Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "File Descriptor Usage",
   "type": "graph",
   "description": "This panel shows the Asterix file descriptor usage (number of file descriptors open / pre set file descriptor max set by Prometheus)",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(process_open_fds / process_max_fds) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}