{
 "title": "Asterix Storage Stats",
 "tags": [
  "asterix",
  "nc"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(asterix_storage_bytes, instance)"
   },
   {
    "name": "partition",
    "query": "label_values(asterix_storage_bytes, partition)"
   },
   {
    "name": "dataverse",
    "query": "label_values(asterix_storage_bytes, dataverse)"
   },
   {
    "name": "dataset",
    "query": "label_values(asterix_storage_bytes, dataset)"
   },
   {
    "name": "index",
    "query": "label_values(asterix_storage_bytes, index)"
   }
  ]
 },
 "panels": [
  {
   "title": "Asterix Storage Size",
   "type": "stat",
   "description": "This panel shows the number of bytes Asterix used in storage for each dataset, index, partition.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(asterix_storage_bytes{instance=~\"$node\", partition=~\"$partition\", dataverse=~\"$dataverse\", dataset=~\"\\\"$dataset\\\"\", index=~\"\\\"$index\\\"\"})",
     "legendFormat": "instance={{instance}}, dataset={{dataset}}, index={{index}}, partition={{partition}}"
    }
   ]
  },
  {
   "title": "Asterix Storage Size Breakdown",
   "type": "graph",
   "description": "This panel shows the breakdown of storage for a given node, partition, dataverse, dataset, and index",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "asterix_storage_bytes{instance=~\"$node\", partition=~\"$partition\", dataverse=~\"$dataverse\", dataset=~\"\\\"$dataset\\\"\", index=~\"\\\"$index\\\"\"}",
     "legendFormat": "node={{instance}}, partition={{partition}}, dataverse={{dataverse}}, dataset={{dataset}}, index={{index}}"
    }
   ]
  },
  {
   "title": "Asterix Storage Size Rate of Increase/Decrease in the last 5 Minutes",
   "type": "graph",
   "description": "This panel shows the rate of increase of the storage sizes of the composite key of dataset, index, and partition. It uses a least squares regression of all the values from the last 30 seconds to calculate the slope",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "deriv(asterix_storage_bytes{instance=~\"$node\", partition=~\"$partition\", dataverse=~\"$dataverse\", dataset=~\"\\\"$dataset\\\"\", index=~\"\\\"$index\\\"\"}[5m])",
     "legendFormat": "instance={{instance}}, dataset={{dataset}}, index={{index}}, partition={{partition}}"
    }
   ]
  }
 ]
}